### ISSUE TITLE
text-field inline label (placeholder?) bug

### ISSUE THREAD

**Issue by john-raymon** [chec/ui-library#156]
![image](https://user-images.githubusercontent.com/30238579/83182729-cc672e80-a0f4-11ea-93ad-4b16d916b5da.png)

**Comment by robbieaverill** [comment]
@ScopeyNZ does #252 for this if we're using labels correctly now?

**Comment by ScopeyNZ** [comment]
No. I think this is related to an extension updating the field without triggering an update to the `:placeholder-shown` pseudo-selector. I don't think there's a fix for this bug.

**Comment by ScopeyNZ** [comment]
Except maybe some JavaScript magic.
