### ISSUE TITLE
visual bug when <text-field> is given a value but no label

### ISSUE THREAD

**Issue by john-raymon** [chec/ui-library#158]
- visual bug when <text-field> is given a value but no label, padding off-set within inner input still renders
![image](https://user-images.githubusercontent.com/30238579/83290526-bd47b580-a1b4-11ea-8fc0-3664170cec2a.png)

**Comment by robbieaverill** [comment]
@john-raymon you still working on this?

**Comment by john-raymon** [comment]
@robbieaverill No I'm not, slipped away. I have to check if this bug still occurs.

**Comment by robbieaverill** [comment]
It does, I saw it recently

**Comment by robbieaverill** [comment]
Fixed in https://github.com/chec/ui-library/pull/257
