### ISSUE TITLE
Clicking off drop downs in modals can lead to accidental closes

### ISSUE THREAD

**Issue by kvisca** [chec/ui-library#231]
**Issue:**
If a user opens a dropdown in a modal the typical user will click out to close that dropdown. If the user mistakenly clicks outside the modal bounds, the user will close the modal and all work will be lost. 

**Solution:**
Catch the click event so the dropdown closes instead of the modal.

**Comment by ScopeyNZ** [comment]
Talking with @dvnkshl - we will just disable clicking the overlay to dismiss.

**Comment by ScopeyNZ** [comment]
This will also involve going through and checking all existing modals already have an option that's not a the provided close button or clicking the overlay.

**Comment by ScopeyNZ** [comment]
We've merged #244 which removes the overlay click. The comment I made around going through and checking modals has been left out as removing the close button on each modal is still up in the air. I'll add that A/C to any task that removes the close button in the future (if any)
