### ISSUE TITLE
Vertical alignment on notifications is off

### ISSUE THREAD

**Issue by ScopeyNZ** [chec/ui-library#234]
Just barely, but still a tiny bit off:

![image](https://user-images.githubusercontent.com/3260989/86624163-b5c7b900-bf77-11ea-9273-609e9b7d181f.png)

**Comment by robbieaverill** [comment]
My bad. I think I did something funky with line height here. Ensure you test with multiple lines of text as well when fixing this.

**Comment by ScopeyNZ** [comment]
Fixed in #253
