### ISSUE TITLE
TextField not focusing when nested within a native form

### ISSUE THREAD

**Issue by john-raymon** [chec/ui-library#238]
Not sure if it's related to https://github.com/chec/ui-library/issues/71. 

But when nesting TextField within a native form element the text-field doesn't focus at all, thus not doing the whole transition from the placeholder-label into an inline label and allowing input of the value. 

To replicate it implement the `text-field` component like this then try to click into it: 
```
      <form class="subscribe-form">
        <p>
          sign up for our newsletter
        </p>
        <div>
          <TextField
            v-model="emailAddress"
            name="subscriber-email-address"
            label="Your email address"
            type="text"
          />
          <BaseButton @click="addSubscriber" class="capitalize" color="primary">
            subscribe
          </BaseButton>
        </div>
      </form>
```

Replacing the form element with a div fixes it.

**Comment by john-raymon** [comment]
Hm 🤔 or may just be that it breaks when there's no width class provided. Gave it a w-auto, or flex-grow and it focuses and works on click.

**Comment by john-raymon** [comment]
Looks like the failing text-field's label's for attribute and input's id attribute don't match when rendering in marketing-site, which may be related to the `uniqueId from '@/lib/helpers/createUniqueId';` module in the text-field.

**Comment by robbieaverill** [comment]
@ScopeyNZ do you think your recent label PR might have fixed this bug?

**Comment by ScopeyNZ** [comment]
No. I think this is related to nuxt SSR and the `createUniqueId` function.

**Comment by ScopeyNZ** [comment]
Actually, it probably will fix this bug, because the label has disabled pointer events now. So clicking on the field will always focus the field.

The label having the wrong `for` attribute with Nuxt SSR will remain an issue though.

**Comment by robbieaverill** [comment]
Reopen if you want
