### ISSUE TITLE
Checkmarks in multi-select dropdowns are not displaying correctly when scrolling.

### ISSUE THREAD

**Issue by dvnkshl** [chec/ui-library#285]
On multi-select dropdowns, checkmark/icons inside of checkboxes are not showing correctly when scrolling.

![2020-09-08 15 46 57](https://user-images.githubusercontent.com/3625028/92534806-9f91df80-f1ea-11ea-9631-ab136abaf5cf.gif)

**Comment by ScopeyNZ** [comment]
😞 I thought I fixed this somewhere but maybe it never made it in.
