### ISSUE TITLE
Figure out a way to separate large images from exported css

### ISSUE THREAD

**Issue by ScopeyNZ** [chec/ui-library#290]
Currently the CSS for the card component is huge as we export a large image within the CSS. We need to figure out a way to ship the image separately, so we can keep the exported CSS small, and instances that use the special card variant can side-load the background image.

**Comment by robbieaverill** [comment]
Use a CDN image URL instead of embedding it?

**Comment by robbieaverill** [comment]
Can this be closed now if we're using the hologram mixin instead of an image?

**Comment by ScopeyNZ** [comment]
Yeah let's close. All the remaining images are SVGs.
