### ISSUE TITLE
InnerBlock div requires flex-grow

### ISSUE THREAD

**Issue by kvisca** [chec/ui-library#301]
InnerBlocks top-level div needs a flex-grow of 1 added to it so that the children display full width.
![Screen Shot 2020-09-24 at 3 42 24 PM](https://user-images.githubusercontent.com/36721153/94192211-a1ab9d80-fe7c-11ea-8a2b-a7c5cbe320a4.png)

`.extra-fields__block-extra > div {
    flex-grow: 1;
}`

**Comment by ScopeyNZ** [comment]
Just for some context, this component has a structure like:

```
<div class="inner-card">
  <div>
    <slot />
  </div>
</div>
```

It does this because it _may_ have an action on the right hand side of the card. I think the first div within this component should have `flex-grow`.

**Comment by robbieaverill** [comment]
Done in #332
