### ISSUE TITLE
Currency text fields with zero value are missing the currency label

### ISSUE THREAD

**Issue by ScopeyNZ** [chec/ui-library#318]
![image](https://user-images.githubusercontent.com/3260989/95140605-22438700-0724-11eb-8c10-731513ae98d0.png)

There's some logic which is casting the value to a bool, which isn't correct. It appears that this logic is driving the `--modified` modifier, which seems opposite to the existing `--empty` modifier that has a better name and has different logic. Maybe we can remove the `--modified` modifier and just use `--empty`?

**Comment by robbieaverill** [comment]
Done in #334
