### ISSUE TITLE
Collapsed accordions have incorrect padding

### ISSUE THREAD

**Issue by robbieaverill** [chec/ui-library#324]
![image](https://user-images.githubusercontent.com/5170590/96022618-f8662080-0e05-11eb-99c1-d9b4a5dd2e88.png)

I thought there was an issue for this already, but couldn't find it. Please close if you do find it!

**Comment by ScopeyNZ** [comment]
This has been fixed. It'll just need an update in whatever project (and maybe a release here).

See https://github.com/chec/ui-library/pull/319

**Comment by robbieaverill** [comment]
Let's close it when it's fixed in the dashboard then, part of our process is updating it when we update the UI lib.

**Comment by ScopeyNZ** [comment]
Do you want to reopen the issue in the dashboard? I feel like that's a more appropriate place to track the issue.
