### ISSUE TITLE
File/image uploader: drag and drop is missing a pointer that indicates it is doing anything

### ISSUE THREAD

**Issue by robbieaverill** [chec/ui-library#325]
When you drag and drop an image into say the product edit screen, it has a "default" pointer cursor. We should use "move" or something to indicate that you're actually doing something.

**Comment by jaepass** [comment]
did some research into this and quite a few logged issues saying this might not be possible. https://github.com/react-dnd/react-dnd/issues/325#issuecomment-239398931. im sure there's still some kind of work around. i've tried hooking into the drag events while dragging operation is happening and still not working:
```
    this.dropzone.on('dragover', this.handleDragover);

    handleDragover(e) {
      e.dataTransfer.effectAllowed = 'move';
    },
```

**Comment by robbieaverill** [comment]
No problem, it was a nice to have anyway. Thank you for looking into it.

**Comment by Tush2890** [comment]
Why this ticket is closed ? Have we already got the solution ?

**Comment by robbieaverill** [comment]
Hi @Tush2890, we closed the ticket for the reasons mentioned above - we've decided not to do it.
