### ISSUE TITLE
Minor WYSIWYG bugs

### ISSUE THREAD

**Issue by ScopeyNZ** [chec/ui-library#330]
> Looks good and works well. Some notes:
> 
> * In dark mode the active buttons in the toolbar need to invert the icon/font colour, ATM it's dark on dark:
>   ![image](https://user-images.githubusercontent.com/5170590/96174454-2dde3d00-0ede-11eb-9eac-ff53b9f2a69d.png)
> * I'd like it if you could resize the thing yourself in the browser, but that's not a blocker
> * When you don't have a label, it still has space for the label. Not sure if that's intended or not, and it's not a blocker

(https://github.com/chec/ui-library/pull/329#pullrequestreview-509682908)

**Comment by robbieaverill** [comment]
![image](https://user-images.githubusercontent.com/5170590/96512654-a7936500-1215-11eb-8275-917a6a1a0649.png)

Is this covered in this issue @kvisca?

**Comment by kvisca** [comment]
> Is this covered in this issue @kvisca?
That appears to be fixed as I can't reproduce it.

**Comment by ScopeyNZ** [comment]
I think Kyle fixed all of the reported issues, except for self-resize. We can raise that as a separate enhancement. No idea how difficult that'll be.
