### ISSUE TITLE
Dropdown chevron shouldn't shrink

### ISSUE THREAD

**Issue by ScopeyNZ** [chec/ui-library#339]
Normal | Shrunk 
--------|--------
![image](https://user-images.githubusercontent.com/3260989/96524244-89852f00-122c-11eb-94b7-2c93116eba56.png) | ![image](https://user-images.githubusercontent.com/3260989/96524181-60649e80-122c-11eb-8a86-349223c57e67.png)

Also, @blazepollard, maybe you want to have some design feedback/review on the mutli-line select happening here?

**Comment by blazepollard** [comment]
The icon should have some padding from text, but shouldn't shrink.

**Comment by kvisca** [comment]
Can't seem to reproduce this @ScopeyNZ. Is this still an issue?

**Comment by ScopeyNZ** [comment]
The story adds a set of options with long labels as a knob on the multi-select story btw.
