### ISSUE TITLE
Tab padding has to be set explicitly in implementation

### ISSUE THREAD

**Issue by jaepass** [chec/ui-library#346]
- `.chec-tab` has a `px-4 py-3` but does not get applied in implementation

<img width="738" alt="Screen Shot 2020-10-22 at 12 35 59 PM" src="https://user-images.githubusercontent.com/48780927/96921626-ad7e8580-1463-11eb-90ec-28ea6b1ee7ed.png">

**Comment by robbieaverill** [comment]
Is this screenshot correct or incorrect? It looks fine to me

**Comment by jaepass** [comment]
this ones the incorrect one with `px-2` `py-6` when it should be `px-3` `py-4` from the ui component

**Comment by ScopeyNZ** [comment]
I think the UI lib is correct:

https://chec-ui.netlify.app/?path=/story/components-tabs--group

Either you implementation hasn't got an up to date UI lib or there's some other styling affecting the tabs.
