### ISSUE TITLE
Update ChecTagGroup button style

### ISSUE THREAD

**Issue by robbieaverill** [chec/ui-library#351]
Looks like this:
![image](https://user-images.githubusercontent.com/5170590/97237775-0d976380-17a5-11eb-9c24-c21cdb745900.png)

New designs look like this:
![image](https://user-images.githubusercontent.com/5170590/97237750-03756500-17a5-11eb-965f-e4b2f35e2c54.png)

**Comment by robbieaverill** [comment]
We also need to reduce the text size from 15px to 12px

**Comment by ScopeyNZ** [comment]
Did https://github.com/chec/ui-library/pull/348 not cover it? It should've

**Comment by robbieaverill** [comment]
Nope, unless the designs #348 was based on were different to the blog page
