### ISSUE TITLE
Clicking anywhere on an accordion should toggle it

### ISSUE THREAD

**Issue by ScopeyNZ** [chec/ui-library#354]
Currently you have to hit the little chevron button, but I think it's nicer UX to be able to hit anywhere along the title of the accordion.

**Comment by robbieaverill** [comment]
cc @blazepollard

**Comment by blazepollard** [comment]
Agreed

**Comment by ScopeyNZ** [comment]
We really need to do this

**Comment by robbieaverill** [comment]
Closed by #581
