### ISSUE TITLE
WYSIWYG content persists when changing between products and one of them has no description

### ISSUE THREAD

**Issue by robbieaverill** [chec/ui-library#410]
Steps to reproduce:

* Open a product that has no description
* Navigate left or right to another product that does
* Go back to the original product

Expected: description of product should be empty again
Actual: description of last viewed product is still shown

**Comment by robbieaverill** [comment]
cc @ScopeyNZ

**Comment by ScopeyNZ** [comment]
This isn't happening for me. Can you give the specific merchant/product involved?

**Comment by ScopeyNZ** [comment]
(I fixed this problem yesterday before the deployment btw)

**Comment by robbieaverill** [comment]
Merchant 17931

* go to products
* search "Satay"
* click "test satay"
* toggle left
* toggle right
* see issue

**Comment by ScopeyNZ** [comment]
Interesting. It's something specific to the face & body roller product

**Comment by robbieaverill** [comment]
👍  feel free to mess around with those products at your leisure. They're throwaway products in my test account.

**Comment by robbieaverill** [comment]
Confirmed this is fixed
