### ISSUE TITLE
Tag field changes height when you add a tag to it

### ISSUE THREAD

**Issue by robbieaverill** [chec/ui-library#436]
![image](https://user-images.githubusercontent.com/5170590/112556436-72bca880-8d87-11eb-8bc2-2694d37f3ae5.png)

When I add a tag to this field it gets slightly bigger vertically:
![image](https://user-images.githubusercontent.com/5170590/112556454-7cdea700-8d87-11eb-953c-24fe47df33d6.png)

It should be the same height in both scenarios.

**Comment by ScopeyNZ** [comment]
See https://github.com/chec/dashboard/issues/714
