### ISSUE TITLE
Unfocussed textarea label no longer has faded drop shadow

### ISSUE THREAD

**Issue by robbieaverill** [chec/ui-library#463]
![image](https://user-images.githubusercontent.com/5170590/118730398-633c6780-b7ec-11eb-8ad5-3544daa76532.png)

The WYSIWYG label used to have a soft faded drop shadow in white (or something like that), so it looked okay over the top of the content. It doesn't any more, and now looks weird with the content in the textarea.

**Comment by robbieaverill** [comment]
Actually I think the label isn't detecting that the field has a value, like it does when text fields have a value:
![image](https://user-images.githubusercontent.com/5170590/118845021-45b8dd80-b880-11eb-967f-fd9a8d5c0880.png)

**Comment by jaepass** [comment]
I can't reproduce this issue with these description WYIWYGs. Where did this come up?
<img width="712" alt="Screen Shot 2021-05-28 at 2 43 39 PM" src="https://user-images.githubusercontent.com/48780927/120044754-4f9ab900-bfc3-11eb-8be6-9cf9adaa4182.png">
<img width="1048" alt="Screen Shot 2021-05-28 at 2 45 04 PM" src="https://user-images.githubusercontent.com/48780927/120044761-5295a980-bfc3-11eb-898f-1a187ce8e5aa.png">

**Comment by robbieaverill** [comment]
The product edit screen in the dashboard

**Comment by robbieaverill** [comment]
I can't reproduce it any more, let's close it :)
