### ISSUE TITLE
Placeholder doesn't always show on tags field

### ISSUE THREAD

**Issue by ScopeyNZ** [chec/ui-library#483]
I can reproduce this in the Storybook example by adding a few tags to make it a multi-line field - the placeholder doesn't show on the new line. If you remove the tags to bring it back to a single line, the placeholder still doesn't show.

**Comment by jaepass** [comment]
This is the same issue as the implemented field in the dashboard, I had set a width to the input there. If we remove the pos-ab on the input element here, it drops to a new line correctly.
