### ISSUE TITLE
Panel header and toolbar scale down when there's a lot of content in the panel

### ISSUE THREAD

**Issue by ScopeyNZ** [chec/ui-library#491]
See this example from the story book:

![image](https://user-images.githubusercontent.com/3260989/127373340-379cff7e-a3c4-4f12-b02a-4eec54401a68.png)

Use the "with content" example, but reduce the screen height.

You can also reproduce more realistically by updating the content so that there's much more content.

**Comment by ScopeyNZ** [comment]
Also fixed by #494 I'm assuming @jaepass?

**Comment by jaepass** [comment]
Yes that's right, fixed by #494
