### ISSUE TITLE
Entering a tag without adding it, and then deleting an existing tag will add your partially added tag

### ISSUE THREAD

**Issue by ScopeyNZ** [chec/ui-library#499]
A picture is worth a thousand words, so a short video at 30 fps is worth lots:

https://user-images.githubusercontent.com/3260989/128579045-29046fa2-d896-404b-9d10-1f256d6030c6.mov

**Comment by jaepass** [comment]
I added this logic to add tags on blur as I've seen some tags field in the wild that uses this pattern. It's the addOnBlur prop -
```
addOnBlur | If the textfield holds a value and loses focus, a tag will be added out of the value
```
We can remove or somehow only detect add on outside click?

**Comment by ScopeyNZ** [comment]
Yeah I think it makes sense to ensure that focus is moved outside of the whole tags component before adding the tag (assuming `addOnBlur === true`).

**Comment by jaepass** [comment]
Ok quick fix I think, will just call `onOutsideClick`
