### ISSUE TITLE
_

### ISSUE THREAD

**Issue by john-raymon** [chec/ui-library#518]

**Comment by john-raymon** [comment]
https://github.com/chec/ui-library/pulls?q=is%3Apr+is%3Aclosed+author%3Ajohn-raymon

**Comment by robbieaverill** [comment]
Hey @john-raymon, the way GitHub works with author contributions is based on the email address used in the commits and whether it's associated with your GitHub account. If you used a @chec.io email address and this is no longer associated with your account, the contributions won't be attributed to your GitHub account. Nevertheless, your commits and your name are permanently etched in the history of this repository. 🙂
