### ISSUE TITLE
Placeholder in text areas does not disappear on iPhone Safari (iOS 14)

### ISSUE THREAD

**Issue by ScopeyNZ** [chec/ui-library#527]
I haven't validated this, but it was reported by a somebody using the docs feedback form on the Commerce.js website from their phone:

> when you type into this input the placeholder doesn’t go away and text is overlapping (iPhone Safari iOS14)

**Comment by kvisca** [comment]
This is no longer an issue, seems Safari has patched whatever was causing this placeholder bug.
