### ISSUE TITLE
Storybook code examples have bad formatting

### ISSUE THREAD

**Issue by ScopeyNZ** [chec/ui-library#537]
![image](https://user-images.githubusercontent.com/3260989/137410128-b9b0665a-f2fa-40b8-a703-e77c840b4b9b.png)

**Comment by kvisca** [comment]
@ScopeyNZ is this referring to the color or the spacing?

**Comment by ScopeyNZ** [comment]
The colour. Is the spacing bad?

**Comment by kvisca** [comment]
Nope, just wanted to check. #563 was a duplicate of this issue so it can be closed.

**Comment by ScopeyNZ** [comment]
Eh? That seems like a completely different issue
