### ISSUE TITLE
ChecTag: should not have a hover state unless it is interactive

### ISSUE THREAD

**Issue by robbieaverill** [chec/ui-library#555]
The ChecTag component has a hover state where it switches from light to dark (with default props). It shouldn't do this because clicking on the tag does nothing by default.

**Comment by jaepass** [comment]
Do you mean we want to remove the hover styles by default? There are instances where we pass a router link in as well.

**Comment by robbieaverill** [comment]
If it's a link or a button it should have a hover state, otherwise it should not.

**Comment by jaepass** [comment]
Ok looks like the ChecTag components uses a button element by default. I think it might need a bit of refactoring, I'll try to come back to this later.
