### ISSUE TITLE
Product screen does not have a mobile responsive view

### ISSUE THREAD

**Issue by jaepass** [chec/ui-library#560]

**Comment by kvisca** [comment]
@jaepass Is this supposed to be on the dashboard? Just a heads up, I have an ongoing HD project to make the entire dashboard responsive. The product screen is mostly complete on that branch already so may not be worth tackling this since I plan to PR it next HD.

**Comment by jaepass** [comment]
Ah shucks wrong repo. Ok sounds good, won't tackle this but will just fix all other views with actions card mobile layout.
