### ISSUE TITLE
Loading indicator z-index is higher than slideout panel mask

### ISSUE THREAD

**Issue by robbieaverill** [chec/ui-library#565]
![image](https://user-images.githubusercontent.com/5170590/142916087-f1888363-a621-486d-8d90-10d4e6fd2bfd.png)

I guess it should be lower than the slideout panel's mask z-index

**Comment by ScopeyNZ** [comment]
This can cause problems putting a loading indicator in the panel.

Loading indicators should have their z-index removed, and just be appropriately positioned in the DOM. Any full page loading in the dashboard can set a top level z-index on its own.

**Comment by robbieaverill** [comment]
The loading indicator in that screenshot is not in the panel, it's in the page before a panel is opened over the top of it

**Comment by ScopeyNZ** [comment]
Sorry "this can cause problems in the panel" means that if you change the z-index to be lower than the panel, loading indicators in the panel won't show properly.
